server:
  Port: 5005
  RunMode: debug
logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
cors:
  allowOrigins: "*"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  minIdleConnections: 100
  poolSize: 5000
  poolTimeout: 240
